In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
print(type(a)) 

<class 'numpy.ndarray'>


In [6]:
A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [7]:
A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Массив чисел с плавающей запятой
print(A)

[[1.1 2.  3. ]
 [3.  4.  5. ]]


In [8]:
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Массив комплексных чисел
print(A)

[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


## Генерация матриц

In [11]:
A = np.arange(4)
print(A)

[0 1 2 3]


In [7]:
np.arange(2, 23, 3)

array([ 2,  5,  8, 11, 14, 17, 20])

In [3]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.empty((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(5, 25, 5)

array([ 5., 10., 15., 20., 25.])

In [13]:
np.logspace(5,25,5)

array([1.e+05, 1.e+10, 1.e+15, 1.e+20, 1.e+25])

In [14]:
np.random.random((2,2))

array([[0.09778088, 0.08558356],
       [0.6958718 , 0.54887837]])

### Изменение формы матрицы

In [12]:
B = np.arange(12).reshape(2, 6)
print(B)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Операции над матрицами

### Сложение

In [13]:
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # сложение соответствующих элементов
print(C)

[[11  1]
 [ 8  0]]


### Умножение

In [31]:
A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)

[[ 36 -12]
 [ -1   2]]


### Умножение на число

In [39]:
С = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
C = С * 10
print(C)

[[10 20 30 40]
 [50 60 70 80]]


### Транспонирование

In [29]:
A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

[[ 1  2  3]
 [ 1  1 -3]]


### Нахождение определителя

In [46]:
A = np.array([[1, 1], [2, 1]])
a = np.linalg.det(A)
print(a)

-1.0
